name: ci

on:
  pull_request:
  workflow_dispatch:

env:
  RUNNER_ARCH: X64
  RUNNER_OS: Linux
  USER: root
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set PR to autocomplete
        run: |
          curl -X 'POST' \
            '${{ env.GITHUB_API_URL }}/repos/kdmorris/thunderbird/pulls/${{ github.event.number }}/merge' \
            -H 'accept: application/json' \
            -H 'Authorization: token ${{ secrets.API_TOKEN }}' \
            -H 'Content-Type: application/json' \
            -d '{ "Do": "merge", "merge_when_checks_succeed": true }'
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
        with:
          source-tag: v0.19.0
      - name: Build
        run: |
          nix build

