name: ci

on:
  pull_request:
  workflow_dispatch:

env:
  RUNNER_ARCH: X64
  RUNNER_OS: Linux
  USER: root
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
        with:
          source-tag: v0.19.0
      - name: Build
        run: |
          nix build

