name: update-sources

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

env:
  RUNNER_ARCH: X64
  RUNNER_OS: Linux
  USER: root
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ SECRETS.GIT_TOKEN }}
      - name: Configure Git
        run: |
          git config user.name "Forgejo Actions Bot"
          git config user.email "<>"
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
        with:
          source-tag: v0.19.0
          extra-conf: |
            substituters = https://attic.letthemplay.tech/system?priority=10 https://cache.nixos.org
            trusted-public-keys = system:UnbWk4457H/fxEuJjW8HnzHdv+CUVE6LMbSd6S4x7Ho= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      - name: Update Sources
        run: |
          nix run .#update
      - name: Create PR
        run: |
          git add beta-sources.json
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Updated Beta Sources"
            git push origin HEAD:refs/for/main -o topic="update-beta-sources" -o title="Update Beta Sources"
            echo '${{ env.GITHUB_API_URL }}/repos/kdmorris/thunderbird/pulls/${{ github.event.number }}/merge'

            curl -X 'POST' \
            '${{ env.GITHUB_API_URL }}/repos/kdmorris/thunderbird/pulls/${{ github.event.number }}/merge' \
            -H 'accept: application/json' \
            -H 'Authorization: token ${{ secrets.API_TOKEN }}' \
            -H 'Content-Type: application/json' \
            -d '{ "Do": "merge", "merge_when_checks_succeed": true }'
          else
            echo "No Changes to Beta Sources";
          fi

