name: ci

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RUNNER_ARCH: X64
  RUNNER_OS: Linux
  USER: root
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
        with:
          source-tag: v0.19.0
          extra-conf: |
            substituters = https://attic.letthemplay.tech/system?priority=10 https://cache.nixos.org
            trusted-public-keys = system:UnbWk4457H/fxEuJjW8HnzHdv+CUVE6LMbSd6S4x7Ho= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      - name: Update Sources
        run: |
          nix run .#update

